# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[(b'PRIMARY', b'PRIMARY'), (b'SECONDARY', b'SECONDARY')], max_length=100)),
                ('sub', models.BooleanField(default=False)),
                ('enemy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_of_commoner', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=300)),
                ('player_limit', models.IntegerField(default=6)),
                ('objective', models.TextField()),
                ('beginning', models.TextField()),
                ('end', models.TextField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.TextField()),
                ('cleared', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='app.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('number_of_rooms', models.IntegerField(default=3)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('activity', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('chapter_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_area', to='app.ChapterArea')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=100)),
                ('full_hp', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=5)),
                ('speed', models.IntegerField(default=5)),
                ('defence', models.IntegerField(default=5)),
                ('dexterity', models.IntegerField(default=5)),
                ('constitution', models.IntegerField(default=5)),
                ('intelligence', models.IntegerField(default=5)),
                ('charisma', models.IntegerField(default=5)),
                ('wisdom', models.IntegerField(default=5)),
                ('inventory_limit', models.FloatField(default=50.0)),
                ('exp', models.IntegerField(default=0)),
                ('initiation', models.IntegerField(default=0)),
                ('attack', models.IntegerField()),
                ('description', models.TextField()),
                ('enemy', models.BooleanField(default=False)),
                ('enemy_type', models.CharField(blank=True, max_length=150, null=True)),
                ('gold', models.IntegerField(default=0)),
                ('alignment', models.CharField(blank=True, max_length=150, null=True)),
                ('hit_dice', models.CharField(blank=True, max_length=100, null=True)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('attack_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_type', to='app.Attack')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hit_dice', models.CharField(max_length=200)),
                ('hp', models.CharField(max_length=200)),
                ('hp_2', models.CharField(max_length=200)),
                ('saving_throws', models.CharField(max_length=150)),
                ('skills_limit', models.IntegerField(default=2)),
                ('skills', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClassLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('pro_bonus', models.IntegerField()),
                ('rage', models.IntegerField(blank=True, null=True)),
                ('rage_dmg', models.IntegerField(blank=True, null=True)),
                ('cantrips', models.IntegerField(blank=True, null=True)),
                ('spells', models.IntegerField(blank=True, null=True)),
                ('martial_art', models.CharField(blank=True, max_length=10, null=True)),
                ('ki_points', models.IntegerField(blank=True, null=True)),
                ('unarmored_mvm', models.IntegerField(blank=True, null=True)),
                ('sneak', models.CharField(max_length=10)),
                ('sorcery_points', models.IntegerField(blank=True, null=True)),
                ('invocations', models.IntegerField(blank=True, null=True)),
                ('spell_slots_1', models.IntegerField(default=0)),
                ('spell_slots_2', models.IntegerField(default=0)),
                ('spell_slots_3', models.IntegerField(default=0)),
                ('spell_slots_4', models.IntegerField(default=0)),
                ('spell_slots_5', models.IntegerField(default=0)),
                ('spell_slots_6', models.IntegerField(default=0)),
                ('spell_slots_7', models.IntegerField(default=0)),
                ('spell_slots_8', models.IntegerField(default=0)),
                ('spell_slots_9', models.IntegerField(default=0)),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_features', to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('ability_score_increase', models.TextField()),
                ('age', models.TextField()),
                ('alignment', models.TextField()),
                ('size', models.TextField()),
                ('speed', models.TextField()),
                ('language', models.TextField()),
                ('sub_race', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRaceTraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('char_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CharacterRace')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobatics', models.IntegerField(default=0)),
                ('anima_hand', models.IntegerField(default=0)),
                ('arcana', models.IntegerField(default=0)),
                ('athletics', models.IntegerField(default=0)),
                ('deception', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
                ('insight', models.IntegerField(default=0)),
                ('intimidation', models.IntegerField(default=0)),
                ('investigation', models.IntegerField(default=0)),
                ('medicine', models.IntegerField(default=0)),
                ('nature', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('persuasion', models.IntegerField(default=0)),
                ('religion', models.IntegerField(default=0)),
                ('soh', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
                ('survival', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lvl_req', models.IntegerField(default=1)),
                ('dextirity', models.IntegerField(blank=True, null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('defence', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='NonPlayableCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('script', models.TextField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('spell_name', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=50)),
                ('rang', models.CharField(max_length=50)),
                ('comp', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('ritual', models.BooleanField(default=False)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('classes', models.ManyToManyField(to='app.CharacterClass')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_request', models.ManyToManyField(related_name='user_request_list', to=settings.AUTH_USER_MODEL)),
                ('friends_list', models.ManyToManyField(related_name='user_friend_list', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='armor',
            field=models.ManyToManyField(related_name='armor_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='tools',
            field=models.ManyToManyField(related_name='tools_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='weapons',
            field=models.ManyToManyField(related_name='weapons_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(related_name='char_inventory', to='app.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='sub_attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_attack_type', to='app.Attack'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_character', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterroom',
            name='npc',
            field=models.ManyToManyField(related_name='room_npc', to='app.NonPlayableCharacters'),
        ),
        migrations.AddField(
            model_name='campaignchapter',
            name='rooms',
            field=models.ManyToManyField(to='app.ChapterRoom'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='chapters',
            field=models.ManyToManyField(related_name='campaign_chapters', to='app.CampaignChapter'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(related_name='campaign_characters', to='app.Character'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(related_name='campaign_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Campaign'),
        ),
        migrations.AddField(
            model_name='battle',
            name='characters',
            field=models.ManyToManyField(related_name='battle_character', to='app.Character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='enemies',
            field=models.ManyToManyField(related_name='enemies', to='app.Character'),
        ),
    ]
