# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-15 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=300)),
                ('player_limit', models.IntegerField(default=6)),
                ('objective', models.TextField()),
                ('begining', models.TextField()),
                ('end', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='app.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEnemies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('initiation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('enemies', models.ManyToManyField(related_name='room_enemies', to='app.CampaignEnemies')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=100)),
                ('damage', models.IntegerField(default=10)),
                ('defence', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=10)),
                ('barter', models.IntegerField(default=10)),
                ('perception', models.IntegerField(default=10)),
                ('inventory_limit', models.FloatField(default=50.0)),
                ('exp', models.IntegerField(default=0)),
                ('initiation', models.IntegerField(default=0)),
                ('attack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[(b'PRIMARY', b'PRIMARY'), (b'SECONDARY', b'SECONDARY')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('defence', models.IntegerField(blank=True, null=True)),
                ('luck', models.IntegerField(blank=True, null=True)),
                ('barter', models.IntegerField(blank=True, null=True)),
                ('perception', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('initiation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('multiple', models.BooleanField(default=False)),
                ('single', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnemyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lvl_req', models.IntegerField(default=1)),
                ('class_exclusive', models.CharField(default=b'All', max_length=150)),
                ('dextirity', models.IntegerField(blank=True, null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('defence', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='NonPlayableCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('script', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='attack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_attack', to='app.EnemyAttack'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='subAttack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_attack', to='app.EnemyAttack'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='app.CharacterClass'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(related_name='char_inventory', to='app.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_character', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapterroom',
            name='npc',
            field=models.ManyToManyField(related_name='room_npc', to='app.NonPlayableCharacters'),
        ),
        migrations.AddField(
            model_name='campaignenemies',
            name='attack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_enemy_attack', to='app.EnemyAttack'),
        ),
        migrations.AddField(
            model_name='campaignenemies',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campaign'),
        ),
        migrations.AddField(
            model_name='campaignenemies',
            name='subAttack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_enemy_attack', to='app.EnemyAttack'),
        ),
        migrations.AddField(
            model_name='campaignchapter',
            name='rooms',
            field=models.ManyToManyField(to='app.ChapterRoom'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='chapters',
            field=models.ManyToManyField(related_name='campaign_chapters', to='app.CampaignChapter'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='chracters',
            field=models.ManyToManyField(related_name='campaign_characters', to='app.Character'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(related_name='campaign_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
