# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('characterclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.CharacterClass')),
            ],
            bases=('app.characterclass',),
        ),
        migrations.AddField(
            model_name='character',
            name='character_race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='character_race', to='app.CharacterRace'),
            preserve_default=False,
        ),
    ]
