# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=150)),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CharacterClass')),
            ],
        ),
    ]
