# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180715_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_request', models.ManyToManyField(related_name='user_request_list', to=settings.AUTH_USER_MODEL)),
                ('friends_list', models.ManyToManyField(related_name='user_friend_list', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='begining',
            new_name='beginning',
        ),
        migrations.AddField(
            model_name='campaign',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
