# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-19 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_characterclassequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('feature', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_class_feature', to='app.CharacterClass')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dextirity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lvl_req',
        ),
        migrations.AddField(
            model_name='item',
            name='armor_class',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='carry_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.CharField(default='1 gp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stealth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
