# Generated by Django 2.1.7 on 2019-04-26 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190331_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='attacks',
        ),
        migrations.AddField(
            model_name='basecharacter',
            name='speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='basecharacter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_character', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='info',
            field=models.ManyToManyField(related_name='enemy_info', to='app.EnemyAction'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='enemies',
            field=models.ManyToManyField(related_name='campaign_enemies', to='app.Enemy'),
        ),
        migrations.AlterField(
            model_name='nonplayablecharacters',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Campaign'),
        ),
    ]
