# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180717_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('number_of_rooms', models.IntegerField(default=3)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='campaignchapter',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterroom',
            name='activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterroom',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterroom',
            name='chapter_area',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_area', to='app.ChapterArea'),
            preserve_default=False,
        ),
    ]
