# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180720_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('characters', models.ManyToManyField(related_name='battle_character', to='app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='campaignenemies',
            name='type',
            field=models.CharField(default='minion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemy',
            name='type',
            field=models.CharField(default='minion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemyattack',
            name='description',
            field=models.TextField(default='minion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='enemies',
            field=models.ManyToManyField(related_name='enemies', to='app.CampaignEnemies'),
        ),
    ]
