# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180920_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
