# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180802_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[(b'PRIMARY', b'PRIMARY'), (b'SECONDARY', b'SECONDARY')], max_length=100)),
                ('sub', models.BooleanField(default=False)),
                ('enemy', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaignenemies',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='campaignenemies',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignenemies',
            name='subAttack',
        ),
        migrations.DeleteModel(
            name='CharacterAttack',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='subAttack',
        ),
        migrations.DeleteModel(
            name='EnemyCategory',
        ),
        migrations.RemoveField(
            model_name='chapterroom',
            name='enemies',
        ),
        migrations.AddField(
            model_name='character',
            name='enemy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='enemy_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='enemy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='battle',
            name='enemies',
            field=models.ManyToManyField(related_name='enemies', to='app.Character'),
        ),
        migrations.DeleteModel(
            name='CampaignEnemies',
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
        migrations.DeleteModel(
            name='EnemyAttack',
        ),
        migrations.AddField(
            model_name='character',
            name='attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_type', to='app.Attack'),
        ),
        migrations.AddField(
            model_name='character',
            name='sub_attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_attack_type', to='app.Attack'),
        ),
    ]
