# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180921_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='container_cap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
