# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-22 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180921_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='weapon_items',
            field=models.ManyToManyField(related_name='weapons_available', to='app.Item'),
        ),
    ]
