# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-11 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180802_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='chracters',
            new_name='characters',
        ),
    ]
