# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180811_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='number_of_commoner',
            field=models.IntegerField(default=0),
        ),
    ]
