# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_characterclass_weapon_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterracetraits',
            name='char_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_race_trait', to='app.CharacterRace'),
        ),
    ]
