# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-12 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_battle_number_of_commoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Campaign'),
        ),
        migrations.AddField(
            model_name='battle',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='description',
            field=models.TextField(default='desciption'),
            preserve_default=False,
        ),
    ]
