# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180922_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='tools_item',
            field=models.ManyToManyField(related_name='tools_available', to='app.Item'),
        ),
    ]
