# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_characterclass_tools_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='c_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='c_race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.CharacterRace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='proficiency_bonus',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throws',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
