# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180925_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_set',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characterskills',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='app.Character'),
        ),
    ]
