# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_nonplayablecharacters_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
