# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_character_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
