# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180925_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background_skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
