# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180819_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClassLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('pro_bonus', models.IntegerField()),
                ('rage', models.IntegerField(blank=True, null=True)),
                ('rage_dmg', models.IntegerField(blank=True, null=True)),
                ('cantrips', models.IntegerField(blank=True, null=True)),
                ('spells', models.IntegerField(blank=True, null=True)),
                ('martial_art', models.CharField(blank=True, max_length=10, null=True)),
                ('ki_points', models.IntegerField(blank=True, null=True)),
                ('unarmored_mvm', models.IntegerField(blank=True, null=True)),
                ('sneak', models.CharField(max_length=10)),
                ('sorcery_points', models.IntegerField(blank=True, null=True)),
                ('invocations', models.IntegerField(blank=True, null=True)),
                ('spell_slots_1', models.IntegerField(default=0)),
                ('spell_slots_2', models.IntegerField(default=0)),
                ('spell_slots_3', models.IntegerField(default=0)),
                ('spell_slots_4', models.IntegerField(default=0)),
                ('spell_slots_5', models.IntegerField(default=0)),
                ('spell_slots_6', models.IntegerField(default=0)),
                ('spell_slots_7', models.IntegerField(default=0)),
                ('spell_slots_8', models.IntegerField(default=0)),
                ('spell_slots_9', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRaceTraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='enemy',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='characterclass_ptr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='class_exclusive',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='armor',
            field=models.ManyToManyField(related_name='armor_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='hit_dice',
            field=models.CharField(default='1d10', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterclass',
            name='hp',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterclass',
            name='hp_2',
            field=models.CharField(default='1d10', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterclass',
            name='saving_throws',
            field=models.CharField(default='saving throws', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skills',
            field=models.CharField(default='None', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skills_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='tools',
            field=models.ManyToManyField(related_name='tools_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='weapons',
            field=models.ManyToManyField(related_name='weapons_category', to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='ability_score_increase',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='age',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='alignment',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='desc',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='language',
            field=models.TextField(default='language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='size',
            field=models.TextField(default='small'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='speed',
            field=models.TextField(default='fast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterrace',
            name='sub_race',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characterracetraits',
            name='char_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CharacterRace'),
        ),
        migrations.AddField(
            model_name='characterclasslevel',
            name='char_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CharacterClass'),
        ),
    ]
