# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_character_background_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='personality_traits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
