# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-03 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180926_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, null=True, to='app.Spells'),
        ),
    ]
