# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-13 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_character_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclasslevel',
            name='slot_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='characterclasslevel',
            name='spell_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
