# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181013_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclasslevel',
            name='sneak',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
