# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181013_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_background', to='app.Character')),
            ],
        ),
    ]
