# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_characterbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bg_skills',
            field=models.IntegerField(default=0),
        ),
    ]
