# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_character_class_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copper', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('electrum', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('platnum', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_currency', to='app.Character')),
            ],
        ),
    ]
