# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_campaignnote_charactercurrency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactercurrency',
            old_name='platnum',
            new_name='platinum',
        ),
    ]
