# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-17 05:42
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190115_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.user_character_img),
        ),
        migrations.AddField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.user_character_thumb),
        ),
    ]
