# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190116_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campaign')),
            ],
        ),
    ]
