# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-29 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_campaignnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('entry', models.TextField()),
                ('posted_on', models.DateField(auto_now=True)),
                ('last_edit', models.DateField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('posted_on', models.DateField(auto_now=True)),
                ('last_edit', models.DateField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forum')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ForumComment')),
            ],
        ),
    ]
